apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dns-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/p4s2wd/dns-config.git  # 存放这些 K8s 清单的仓库
    targetRevision: HEAD
    path: k8s  # YAML 文件存放目录
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m