apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9-git
  namespace: dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind9-git
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bind9-git
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: "k8s-node01"
      # Pod级别的securityContext (用于init操作)
      securityContext:
        runAsUser: 0  # 临时使用root进行git操作
      containers:
      - name: bind9
        image: docker.1ms.run/ubuntu/bind9:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          # 安装git
          apt-get update && apt-get install -y git
          
          git config --global user.email "p4s2wd@gmail.com"
          git config --global user.name "p4s2wd"
          git config --global --add safe.directory /etc/bind
          git config --global https.proxy https://192.168.2.135:7890
          git clone https://github.com/p4s2wd/dns-config.git /etc/bind
          
          # 设置权限
          chown -R 100:101 /etc/bind
          find /etc/bind -type d -exec chmod 755 {} \;
          find /etc/bind -type f -exec chmod 644 {} \;
          
          cd /etc/bind
          /monitor.sh &
          exec su -s /bin/sh -c "exec named -g -c /etc/bind/config/named.conf" bind
        ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
          protocol: TCP
        - containerPort: 953
          protocol: TCP
        # 容器级别的securityContext (用于运行BIND9)
        securityContext:
          capabilities:
            add: ["NET_BIND_SERVICE"]
          runAsUser: 0
        
        env:
        - name: TZ
          value: Asia/Shanghai
        volumeMounts:
        - name: bind-config
          mountPath: /etc/bind
        - name: monitor-script
          mountPath: /monitor.sh
          subPath: monitor.sh
        
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "ps -efwww | grep named >/dev/null 2>&1"
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 5
        
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
      
      volumes:
      - name: bind-config
        emptyDir: {}
      - name: monitor-script
        configMap:
          name: bind-monitor-script
          defaultMode: 0755  # 确保有执行权限
